disabled_rules:
- trailing_whitespace
- force_cast
- private_over_fileprivate
- force_try
- empty_enum_arguments
- class_delegate_protocol
- identifier_name
- nesting
- line_length
- empty_parentheses_with_trailing_closure
- unused_setter_value
- unused_closure_parameter
- file_length
- for_where
- type_body_length
- weak_delegate
- type_name
- cyclomatic_complexity
- function_bodo_length
- operator_whitespace
- function_body_length
